### ISSUE TITLE
Docker Daemon required?

### ISSUE THREAD

**Issue by Lucius201** [mavi888/cdk-typescript-lambda#2]
Hi,
i have some issues trying to deploy NodeJsFunctions. For me I always get an error message, that docker daemon isn`t running. Do I need Docker Daemon for NodeJsFunctions or is there different ways for deploying my lambda to the cloud. Note: I am not trying to deploy it locally and i am using TypeScript even for the handler file. Maybe somebody can help me.
Regards Lucius

**Comment by GunnerSkaleHD** [comment]
.
